### ISSUE TITLE
FileNotFoundError: [Errno 2]

### ISSUE THREAD

**Issue by joaquin-becerra** [wdekkers/docker-php7-httpd-apache2-mysql#1]
Hi!!

I get:

FileNotFoundError: [Errno 2] No such file or directory: '/etc/docker/dockerfile_php_7'

seems like the path in the socker-compose.yml is wrong
It say:
    dockerfile: /etc/docker/dockerfile_php_7
Should say:
     dockerfile: **.**/etc/docker/dockerfile_php_7

**Comment by wdekkers** [comment]
Hi @joaquin-becerra  good catch there was a PR raised by @lemil that I just merged and addresses this issue. https://github.com/wdekkers/docker-php7-httpd-apache2-mysql/pull/2
